[build]
buildCommand = "prisma generate && next build"

[deploy]
startCommand = "next start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
